FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:249 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x8004213702 0x800420a18e 0x8004218aec 0x80042074d3
Translation of call stack:
0x0000008004213702: debug_panic (lib/kernel/debug.c:32)
0x000000800420a18e: lock_release (threads/synch.c:251)
0x0000008004218aec: h_thread_func (tests/threads/priority-donate-sema.c:81)
0x00000080042074d3: kernel_thread (threads/thread.c:468)
